- name: Example Playbook with Conditions
  hosts: all
  remote_user: ubuntu
  become: true
  tasks:
    - name: Task 1 (conditional)
      apt: 
        name: apache2
        state: present
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
    - name:
      debug:
        msg: "{{ansible_kernel_version}}"
    - name: Example Playbook with Loop
      debug:
        msg: "{{ item }}"
        loop:
          - Apple
          - Banana
          - Orange




    # - name: Task 2 (conditional with multiple conditions)
    #   debug:
    #     msg: "Task 2 executed"
    #   when:
    #     - ansible_distribution == "Ubuntu"
    #     - ansible_distribution_major_version|int >= 20

